### ISSUE TITLE
Shut-off option

### ISSUE THREAD

**Issue by mjohnson11** [cmudig/AutoProfiler#124]
It's possible I've missed some existing way to do this, but I couldn't figure out how using the extension or jupyter lab in general. Basically I'd like to be able to completely turn off autoprofiler and have it clear its memory and not do anything. I'm currently working with very large dataframes and I think autoprofiler is causing a lot of slow down, so I just uninstalled it, but I would have preferred to just shut it down instead if that was possible!

**Comment by willeppy** [comment]
Hey thanks for filing this! Totally agree. Right now AP computes profiles even when the tab is not open so is adding unnecessary overhead, I will look into this soon and hopefully a pretty easy fix because I agree very annoying right now

**Comment by willeppy** [comment]
Hey @mjohnson11 just merged in a fix that should only update the data in AutoProfiler when it is actually open and visible so should not cause slow downs if not visible. It will be included in our next release!

**Comment by mjohnson11** [comment]
Great, I will plan to redownload it!
