### ISSUE TITLE
hide "connected to"

### ISSUE THREAD

**Issue by domoritz** [cmudig/AutoProfiler#55]
I'm not sure what purpose this serves.

<img width="339" alt="Screenshot 2022-10-12 at 11 46 18" src="https://user-images.githubusercontent.com/589034/195388904-7be5b812-4898-48c0-99f5-1b22b0012a21.png">

**Comment by willeppy** [comment]
If you have multiple notebooks open with the same dataframe names then kind of nice to know you're looking at the right notebook?
